### ISSUE TITLE
Double sign-in requests

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#347]
**Describe the bug**
Metamask sends double sign-in requests.

**Version:** [3.0.0-develop.3](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.3)

**To Reproduce**
1. Connect your Metamask wallet to the Portal
2. Change account in Metamask
3. Click on "Add to Favorites"
4. See double sign-in requests in Metamask

**Expected behavior**
There is only 1 sign-in request

**Screenshots**

https://github.com/user-attachments/assets/d600491b-757d-4f6f-9691-1d59d9b0f1fc

**Comment by dmytrotkk** [comment]
The problem appears because after switching wallet in Metamask sign-in request is sent in the background, without a new popup message, it can be open manually by clicking on Metamask extension after switching account:


https://github.com/user-attachments/assets/685a11d2-2934-4816-b5e6-90c47456168f


If user do not accept this request, after clicking on "Sign-in" button, the second request is sent.
